#################
### AUTOSTART ###
#################

# Start daemons and background applications
exec-once = nm-applet --indicator &
exec-once = swaync &
exec-once = blueman-applet &
exec-once = waybar &
exec-once = systemctl --user start hyprpolkitagent &

# Start graphical applications
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 1 silent] $systemMonitor
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser

# clipboard management
exec-once = cliphist wipe # wipe clipboard history on every login
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
