##############################
### WINDOWS AND WORKSPACES ###
##############################

# nm-connection-editor
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = size (monitor_w*0.45) (monitor_h*0.45), match:class ^(nm-connection-editor)$
windowrule = center on, match:class ^(nm-connection-editor)$

# xdg-desktop-portal-gtk
windowrule = float on,match:class (xdg-desktop-portal-gtk)
windowrule = size (monitor_w*0.5) (monitor_h*0.5),match:class (xdg-desktop-portal-gtk)

# pavucontrol
windowrule = float on,match:class (org.pulseaudio.pavucontrol)
windowrule = size (monitor_w*0.5) (monitor_h*0.5),match:class (org.pulseaudio.pavucontrol)

# blueman-manager
windowrule = float on,match:class (blueman-manager)
windowrule = size (monitor_w*0.5) (monitor_h*0.5),match:class (blueman-manager)

# mpv
windowrule = opacity 1.0 override 1.0 override,match:class (mpv)
windowrule = idle_inhibit always,match:class (mpv)

# vlc
windowrule = opacity 1.0 override 1.0 override,match:class (vlc)
windowrule = idle_inhibit always,match:class (vlc)

# steam
windowrule = opacity 1.0 override 1.0 override,match:class (steam)

# zen-browser
windowrule = workspace 2,match:class zen

# firefox
windowrule = workspace 2,match:class firefox
windowrule = workspace 2,match:class firefox-developer-edition

# nemo
windowrule = float on, match:class nemo, match:title .* Properties$
windowrule = size (monitor_w*0.5) (monitor_h*0.5), match:class nemo, match:title .* Properties$
windowrule = center on, match:class nemo, match:title .* Properties$

# Dialog windows – float+center these windows.
windowrule = center on, match:title ^(Open File)(.*)$
windowrule = center on, match:title ^(Select a File)(.*)$
windowrule = center on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, match:title ^(Open Folder)(.*)$
windowrule = center on, match:title ^(Save As)(.*)$
windowrule = center on, match:title ^(Library)(.*)$
windowrule = center on, match:title ^(File Upload)(.*)$
windowrule = float on, match:title ^(Open File)(.*)$
windowrule = float on, match:title ^(Select a File)(.*)$
windowrule = float on, match:title ^(Choose wallpaper)(.*)$
windowrule = float on, match:title ^(Open Folder)(.*)$
windowrule = float on, match:title ^(Save As)(.*)$
windowrule = float on, match:title ^(Library)(.*)$
windowrule = float on, match:title ^(File Upload)(.*)$

# --- Tearing ---
windowrule = immediate on, match:title .*\.exe
windowrule = immediate on, match:class ^(steam_app)

# Disable blur for XWayland windows (or context menus with shadow would look weird)
windowrule = no_blur on, match:xwayland 1

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0
