import = [
    "~/.config/alacritty/themes/github_dark_dimmed.toml"
]

[window]
opacity = 0.9

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
