FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.2-alpine AS build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /build

RUN apk add --no-cache gcc musl-dev ca-certificates
RUN echo "app:x:10001:10001:App User:/:/sbin/nologin" > /etc/minimal-passwd

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags='-s -extldflags "-static"' -o server -v ./cmd/server
RUN update-ca-certificates

FROM scratch AS prod

ENV SERVER_PORT=8080

COPY --from=build /etc/ssl/ca-certificates.crt /etc/ssl/ca-certificates.crt
COPY --from=build /etc/minimal-passwd /etc/passwd
COPY --from=build /build/server /server

VOLUME /database
USER app
EXPOSE ${SERVER_PORT}

ENTRYPOINT ["/server"]
