gui:
  shortTimeFormat: "14:00"
  showRandomTip: false
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: onlyArrow
  # Catppuccin Mocha Blue
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
git:
  commit:
    signOff: true
  merging:
    manualCommit: true
  parseEmoji: true
